### ISSUE TITLE
Ability to use a common org-wide yaml config?

### ISSUE THREAD

**Issue by aaronsteers** [Ezard/semantic-prs#227]
Hello! We've been using this app happily for quite a while now and we want to expand to have it enabled on all repos in our org.

Would it be possible for the GitHub App to look for org-wide config defaults in a specific repo within the org?

So the decision tree would then be:

1. If the repo has a `semantic.yml` file, use it.
2. Else if the org has a centrally available `semantic.yml` file, use it.
3. Else, use the GitHub App defaults.

**Comment by Ezard** [comment]
Hey @aaronsteers!

I think that this *should* already be supported, based on [Probot's docs here](https://probot.github.io/docs/best-practices/#store-configuration-in-the-repository)

So if your org name is `acme-corp`, then you'd create a new repo within the org that's also called `acme-corp` and put the config in `.github/semantic.yml`, as usual. This should follow the decision tree that you listed above, although I haven't tested this myself so if it doesn't work as expected then let me know and I'll look into it further :)

**Comment by aaronsteers** [comment]
Very cool! We'll try this out and report back. Thanks, @Ezard

**Comment by Ezard** [comment]
@aaronsteers did everything work as expected for you?

**Comment by aaronsteers** [comment]
It worked great! Thank you! 🙏
