### ISSUE TITLE
Semantic PR check is false even there are commits started with "feat: "

### ISSUE THREAD

**Issue by pawellabaj** [Ezard/semantic-prs#357]
### Describe the bug

I have a PR (https://github.com/pawellabaj/auto-record/pull/102) with many commits with message: _"feat: Allowed to implement extension for compact constructor updating"_, eg. https://github.com/pawellabaj/auto-record/pull/102/commits/c3a6c50ddca7757849d3ced09ac39751bfcfe145

Semantic PR is false

### semantic.yml contents

n/a

### Sample Commit Message(s) (if relevant)

feat: Allowed to implement extension for compact constructor updating

**Comment by Ezard** [comment]
@pawellabaj this is because you have multiple commits in that PR

By default, if there are multiple commits then the PR title is checked, and in this case your title is not semantic

This behaviour can be changed via the config file if you want (I'm happy to help you choose which options are right for you - just let me know the behaviour that you're looking for 🙂)

**Comment by pawellabaj** [comment]
Thank you @Ezard for the explanation.

I didn't understand the documentation at the beginning

**Comment by pawellabaj** [comment]
I added [.github/semantic.yml](https://github.com/pawellabaj/auto-record/blob/feature/issue-28-allow-user-to-provide-additional-compact-constructor-method-cont/.github/semantic.yml) with following content:
```
titleAndCommits: true
anyCommit: true
```

And it didn't help.
What am I missing?

**Comment by pawellabaj** [comment]
I switched te default behaviour

**Comment by Ezard** [comment]
@pawellabaj your original config didn't work because you specified `titleAndCommits: true`, which means that both the title and the commits must be semantic

If you use:
```
commitsOnly: true
anyCommit: true
```
then just 1 commit in the PR needs to be semantic - the title and the rest of the commits can be anything
