### ISSUE TITLE
Details report the violations

### ISSUE THREAD

**Issue by tisonkun** [Ezard/semantic-prs#36]
Currently, if semantic-prs reports fails, the "details" button jump to this repo instead of a concrete info about violations.

**Comment by Ezard** [comment]
@tisonkun the check currently shows an inline error message (e.g. `add a semantic commit or PR title`), which should be enough to resolve the issue; what additional information would you like to be displayed when you click on the "Details" link?

**Comment by tisonkun** [comment]
@Ezard oops. Yes there is a message which keeps the same behavior of semantic-pull-requests. Sorry for bothering.
