### ISSUE TITLE
Enable Semantic PRs doesn't apply for existing PRs

### ISSUE THREAD

**Issue by tisonkun** [Ezard/semantic-prs#38]
After enable Semantic PRs on bytebase/bytebase and close & reopen PR https://github.com/bytebase/bytebase/pull/1445, it seems Semantic PRs app doesn't report the status. Only new (created) PRs will trigger the App.

Is it possible to (re)check and report the status when a PR is reopened?

**Comment by tisonkun** [comment]
After a new commit pushed, it seems this App is triggered. Keep open for @Ezard's opinion.

**Comment by Ezard** [comment]
@tisonkun unfortunately I don't think there's a way for it to be triggered on PRs that are already open 😔 (although I'm happy to be proved wrong if you know how to do this haha)

I can definitely add a trigger for when PRs are reopened though, sure!
I'm pretty busy today and tomorrow, so I'll probably implement this on Thursday

**Comment by tisonkun** [comment]
> I don't think there's a way for it to be triggered on PRs that are already open.

Haha, I think so.

> I can definitely add a trigger for when PRs are reopened though, sure!
> I'm pretty busy today and tomorrow, so I'll probably implement this on Thursday

Thank you! Take your spare time :)
