### ISSUE TITLE
support spaces in scopes

### ISSUE THREAD

**Issue by scarf005** [Ezard/semantic-prs#478]
## Current Situation

`feat(foo, bar): baz` -> Fails
`feat(foo,bar): baz` -> OK

## Expected Situation

`feat(foo, bar): baz` -> OK
`feat(foo,bar): baz` -> OK

I'm willing to open a PR.

**Comment by Ezard** [comment]
Thanks for the suggestion @scarf005 - this has now been merged, and will be deployed soon 🙂
